# Generated by Django 4.1.8 on 2023-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_menuitems_creation_date_menuitems_is_new_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
